# Generated by Django 4.1.3 on 2023-04-23 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0004_myuser_groups_myuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.recipe'),
        ),
    ]
