# Generated by Django 4.1.3 on 2023-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0005_alter_recipestep_recipe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.CharField(blank=True, max_length=900000, null=True),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='photo',
            field=models.CharField(blank=True, max_length=900000, null=True),
        ),
    ]
