# Generated by Django 4.1.3 on 2023-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0006_recipe_photo_recipestep_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.BinaryField(blank=True, max_length=900000, null=True),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='photo',
            field=models.BinaryField(blank=True, max_length=900000, null=True),
        ),
    ]
