# Generated by Django 4.1.3 on 2023-04-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0009_alter_product_name_alter_recipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipecomment',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipecomment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipeproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='recipeproduct',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipeproduct',
            old_name='unit_id',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='reciperate',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipestep',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shoppinglistproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shoppinglistproduct',
            old_name='shopping_list_id',
            new_name='shopping_list',
        ),
    ]
